#!/usr/bin/env bash
# Installs nginx on web server and configures
#nginx to listen on port 80
sudo apt-get -y update
sudo apt-get install -y nginx
mkdir /etc/nginx/html
ufw allow 'Nginx HTTP'
echo "Hello World!" > /etc/nginx/html/index.html
echo "server {
        listen 80 default_server;
 	listen [::]:80 default_server;

	root /etc/nginx/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;
}" > /etc/nginx/sites-available/default
service nginx start
