#!/usr/bin/env bash
Configure your Nginx server so that /redirect_me is redirecting to another page.

# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create index.html file with "Hello World"
echo "Hello World!" > /var/www/html/index.html

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx for redirection
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 http://www.redirectedpage.com;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF'

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart nginx service to apply changes
sudo service nginx restart

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'
