#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create index.html file with "Hello World"
echo "Hello World!" > /var/www/html/index.html

# Create redirect configuration file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 http://www.redirectedpage.com;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default

# Restart nginx service to apply changes
service nginx restart
