#!/bin/bash
#configures nginx server to have custom 404 page
#that contains the string Ceci n'est pas une page

# Install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom 404 error page with the required string
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/custom_404.html

# Create a configuration file for the custom 404 page
sudo sh -c 'echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /etc/nginx/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }

    location /redirect_me {
        return 301 http://www.redirectedpage.com;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default'

# Restart Nginx to apply changes
sudo service nginx restart

# Output success message
echo "Nginx configured with a custom 404 page."

