#!/usr/bin/env bash
#confugures nginx server to have a custom 404 page
#that contains the string Ceci n'est pas une page

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set up website files and permissions
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

#Create backup of the default index file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index file with "Hello World!"
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Set up redirection from /redirect_me to a YouTube video
sudo sed -i '/server_name _;/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Set up a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sudo sed -i '/error_page 404 \/404.html;/a \\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

echo -e "\nCompleted. Nginx configured. ✅\n"
