#!/usr/bin/env bash
# Installs and configures HAproxy on my Ib-01 server
sudo pt-get update
sudo apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 465216-web-01 52.23.213.201:80 check\n\tserver 465216-web-02 52.91.160.173:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
